/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : string,
  'resolved' : boolean,
  'alertType' : AlertType,
  'assetId' : string,
  'message' : string,
  'timestamp' : bigint,
  'severity' : AlertSeverity,
}
export type AlertSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type AlertType = { 'geofenceBreach' : null } |
  { 'tempExceeded' : null } |
  { 'shockDetected' : null } |
  { 'humidityAlert' : null } |
  { 'signalLost' : null };
export interface Asset {
  'id' : string,
  'status' : AssetStatus,
  'destination' : string,
  'cargoType' : CargoType,
  'name' : string,
  'createdAt' : bigint,
  'origin' : string,
  'assetType' : AssetType,
}
export type AssetStatus = { 'alert' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null } |
  { 'onHold' : null };
export type AssetType = { 'truck' : null } |
  { 'aircraft' : null } |
  { 'vessel' : null } |
  { 'container' : null };
export type CargoType = { 'equipment' : null } |
  { 'medical' : null } |
  { 'pharmaceutical' : null };
export interface CustodyEvent {
  'id' : string,
  'assetId' : string,
  'notes' : string,
  'timestamp' : bigint,
  'location' : string,
  'custodian' : string,
  'eventType' : EventType,
}
export interface DeviceConfig {
  'id' : bigint,
  'sf' : bigint,
  'txp' : bigint,
  'configured_by' : string,
  'status' : boolean,
  'mode' : bigint,
  'device_id' : bigint,
  'created_at' : bigint,
  'CAN_id' : bigint,
  'endpoint_URL' : string,
  'RFID_enable' : boolean,
  'frequency' : bigint,
  'client_id' : bigint,
  'thresholds' : Array<[string, string]>,
  'config_timestamp' : bigint,
  'debug_enable' : boolean,
  'SD_enable' : boolean,
}
export interface DeviceConfigInput {
  'sf' : bigint,
  'txp' : bigint,
  'configured_by' : string,
  'status' : boolean,
  'mode' : bigint,
  'device_id' : bigint,
  'CAN_id' : bigint,
  'endpoint_URL' : string,
  'RFID_enable' : boolean,
  'frequency' : bigint,
  'client_id' : bigint,
  'thresholds' : Array<[string, string]>,
  'config_timestamp' : bigint,
  'debug_enable' : boolean,
  'SD_enable' : boolean,
}
export interface ETA {
  'originPort' : string,
  'assetId' : string,
  'destinationPort' : string,
  'distanceKm' : number,
  'departedAt' : bigint,
  'estimatedArrival' : bigint,
  'currentSpeedKnots' : number,
}
export type EventType = { 'checkpoint' : null } |
  { 'pickup' : null } |
  { 'delivery' : null } |
  { 'transfer' : null };
export interface Telemetry {
  'id' : string,
  'latitude' : number,
  'shockG' : number,
  'assetId' : string,
  'temperature' : number,
  'satelliteSignal' : number,
  'humidity' : number,
  'longitude' : number,
  'timestamp' : bigint,
}
export interface TelemetryHistory {
  'assetId' : string,
  'readings' : Array<Telemetry>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAsset' : ActorMethod<[Asset], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlert' : ActorMethod<[Alert], undefined>,
  'getAsset' : ActorMethod<[string], [] | [Asset]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustodyChain' : ActorMethod<[string], Array<CustodyEvent>>,
  'getETA' : ActorMethod<[string], [] | [ETA]>,
  'getLatestDeviceConfig' : ActorMethod<[bigint], [] | [DeviceConfig]>,
  'getLatestTelemetry' : ActorMethod<[string], [] | [Telemetry]>,
  'getTelemetryHistory' : ActorMethod<[string, bigint], TelemetryHistory>,
  'getUnresolvedAlerts' : ActorMethod<[], Array<Alert>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAssets' : ActorMethod<[], Array<Asset>>,
  'recordCustodyEvent' : ActorMethod<[CustodyEvent], undefined>,
  'recordTelemetry' : ActorMethod<[Telemetry], undefined>,
  'resolveAlert' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'setDeviceConfig' : ActorMethod<[DeviceConfigInput], DeviceConfig>,
  'updateETA' : ActorMethod<[ETA], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];