/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssetStatus = IDL.Variant({
  'alert' : IDL.Null,
  'inTransit' : IDL.Null,
  'delivered' : IDL.Null,
  'onHold' : IDL.Null,
});
export const CargoType = IDL.Variant({
  'equipment' : IDL.Null,
  'medical' : IDL.Null,
  'pharmaceutical' : IDL.Null,
});
export const AssetType = IDL.Variant({
  'truck' : IDL.Null,
  'aircraft' : IDL.Null,
  'vessel' : IDL.Null,
  'container' : IDL.Null,
});
export const Asset = IDL.Record({
  'id' : IDL.Text,
  'status' : AssetStatus,
  'destination' : IDL.Text,
  'cargoType' : CargoType,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'origin' : IDL.Text,
  'assetType' : AssetType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlertType = IDL.Variant({
  'geofenceBreach' : IDL.Null,
  'tempExceeded' : IDL.Null,
  'shockDetected' : IDL.Null,
  'humidityAlert' : IDL.Null,
  'signalLost' : IDL.Null,
});
export const AlertSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Text,
  'resolved' : IDL.Bool,
  'alertType' : AlertType,
  'assetId' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : AlertSeverity,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EventType = IDL.Variant({
  'checkpoint' : IDL.Null,
  'pickup' : IDL.Null,
  'delivery' : IDL.Null,
  'transfer' : IDL.Null,
});
export const CustodyEvent = IDL.Record({
  'id' : IDL.Text,
  'assetId' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
  'custodian' : IDL.Text,
  'eventType' : EventType,
});
export const ETA = IDL.Record({
  'originPort' : IDL.Text,
  'assetId' : IDL.Text,
  'destinationPort' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'departedAt' : IDL.Int,
  'estimatedArrival' : IDL.Int,
  'currentSpeedKnots' : IDL.Float64,
});
export const DeviceConfig = IDL.Record({
  'id' : IDL.Nat,
  'sf' : IDL.Nat,
  'txp' : IDL.Nat,
  'configured_by' : IDL.Text,
  'status' : IDL.Bool,
  'mode' : IDL.Nat,
  'device_id' : IDL.Nat,
  'created_at' : IDL.Int,
  'CAN_id' : IDL.Nat,
  'endpoint_URL' : IDL.Text,
  'RFID_enable' : IDL.Bool,
  'frequency' : IDL.Nat,
  'client_id' : IDL.Nat,
  'thresholds' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'config_timestamp' : IDL.Int,
  'debug_enable' : IDL.Bool,
  'SD_enable' : IDL.Bool,
});
export const Telemetry = IDL.Record({
  'id' : IDL.Text,
  'latitude' : IDL.Float64,
  'shockG' : IDL.Float64,
  'assetId' : IDL.Text,
  'temperature' : IDL.Float64,
  'satelliteSignal' : IDL.Float64,
  'humidity' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const TelemetryHistory = IDL.Record({
  'assetId' : IDL.Text,
  'readings' : IDL.Vec(Telemetry),
});
export const DeviceConfigInput = IDL.Record({
  'sf' : IDL.Nat,
  'txp' : IDL.Nat,
  'configured_by' : IDL.Text,
  'status' : IDL.Bool,
  'mode' : IDL.Nat,
  'device_id' : IDL.Nat,
  'CAN_id' : IDL.Nat,
  'endpoint_URL' : IDL.Text,
  'RFID_enable' : IDL.Bool,
  'frequency' : IDL.Nat,
  'client_id' : IDL.Nat,
  'thresholds' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'config_timestamp' : IDL.Int,
  'debug_enable' : IDL.Bool,
  'SD_enable' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAsset' : IDL.Func([Asset], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlert' : IDL.Func([Alert], [], []),
  'getAsset' : IDL.Func([IDL.Text], [IDL.Opt(Asset)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustodyChain' : IDL.Func([IDL.Text], [IDL.Vec(CustodyEvent)], ['query']),
  'getETA' : IDL.Func([IDL.Text], [IDL.Opt(ETA)], ['query']),
  'getLatestDeviceConfig' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(DeviceConfig)],
      ['query'],
    ),
  'getLatestTelemetry' : IDL.Func([IDL.Text], [IDL.Opt(Telemetry)], ['query']),
  'getTelemetryHistory' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [TelemetryHistory],
      ['query'],
    ),
  'getUnresolvedAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'recordCustodyEvent' : IDL.Func([CustodyEvent], [], []),
  'recordTelemetry' : IDL.Func([Telemetry], [], []),
  'resolveAlert' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'setDeviceConfig' : IDL.Func([DeviceConfigInput], [DeviceConfig], []),
  'updateETA' : IDL.Func([ETA], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssetStatus = IDL.Variant({
    'alert' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
    'onHold' : IDL.Null,
  });
  const CargoType = IDL.Variant({
    'equipment' : IDL.Null,
    'medical' : IDL.Null,
    'pharmaceutical' : IDL.Null,
  });
  const AssetType = IDL.Variant({
    'truck' : IDL.Null,
    'aircraft' : IDL.Null,
    'vessel' : IDL.Null,
    'container' : IDL.Null,
  });
  const Asset = IDL.Record({
    'id' : IDL.Text,
    'status' : AssetStatus,
    'destination' : IDL.Text,
    'cargoType' : CargoType,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'origin' : IDL.Text,
    'assetType' : AssetType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlertType = IDL.Variant({
    'geofenceBreach' : IDL.Null,
    'tempExceeded' : IDL.Null,
    'shockDetected' : IDL.Null,
    'humidityAlert' : IDL.Null,
    'signalLost' : IDL.Null,
  });
  const AlertSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Text,
    'resolved' : IDL.Bool,
    'alertType' : AlertType,
    'assetId' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : AlertSeverity,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EventType = IDL.Variant({
    'checkpoint' : IDL.Null,
    'pickup' : IDL.Null,
    'delivery' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const CustodyEvent = IDL.Record({
    'id' : IDL.Text,
    'assetId' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
    'custodian' : IDL.Text,
    'eventType' : EventType,
  });
  const ETA = IDL.Record({
    'originPort' : IDL.Text,
    'assetId' : IDL.Text,
    'destinationPort' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'departedAt' : IDL.Int,
    'estimatedArrival' : IDL.Int,
    'currentSpeedKnots' : IDL.Float64,
  });
  const DeviceConfig = IDL.Record({
    'id' : IDL.Nat,
    'sf' : IDL.Nat,
    'txp' : IDL.Nat,
    'configured_by' : IDL.Text,
    'status' : IDL.Bool,
    'mode' : IDL.Nat,
    'device_id' : IDL.Nat,
    'created_at' : IDL.Int,
    'CAN_id' : IDL.Nat,
    'endpoint_URL' : IDL.Text,
    'RFID_enable' : IDL.Bool,
    'frequency' : IDL.Nat,
    'client_id' : IDL.Nat,
    'thresholds' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'config_timestamp' : IDL.Int,
    'debug_enable' : IDL.Bool,
    'SD_enable' : IDL.Bool,
  });
  const Telemetry = IDL.Record({
    'id' : IDL.Text,
    'latitude' : IDL.Float64,
    'shockG' : IDL.Float64,
    'assetId' : IDL.Text,
    'temperature' : IDL.Float64,
    'satelliteSignal' : IDL.Float64,
    'humidity' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const TelemetryHistory = IDL.Record({
    'assetId' : IDL.Text,
    'readings' : IDL.Vec(Telemetry),
  });
  const DeviceConfigInput = IDL.Record({
    'sf' : IDL.Nat,
    'txp' : IDL.Nat,
    'configured_by' : IDL.Text,
    'status' : IDL.Bool,
    'mode' : IDL.Nat,
    'device_id' : IDL.Nat,
    'CAN_id' : IDL.Nat,
    'endpoint_URL' : IDL.Text,
    'RFID_enable' : IDL.Bool,
    'frequency' : IDL.Nat,
    'client_id' : IDL.Nat,
    'thresholds' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'config_timestamp' : IDL.Int,
    'debug_enable' : IDL.Bool,
    'SD_enable' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAsset' : IDL.Func([Asset], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlert' : IDL.Func([Alert], [], []),
    'getAsset' : IDL.Func([IDL.Text], [IDL.Opt(Asset)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustodyChain' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CustodyEvent)],
        ['query'],
      ),
    'getETA' : IDL.Func([IDL.Text], [IDL.Opt(ETA)], ['query']),
    'getLatestDeviceConfig' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(DeviceConfig)],
        ['query'],
      ),
    'getLatestTelemetry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Telemetry)],
        ['query'],
      ),
    'getTelemetryHistory' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [TelemetryHistory],
        ['query'],
      ),
    'getUnresolvedAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'recordCustodyEvent' : IDL.Func([CustodyEvent], [], []),
    'recordTelemetry' : IDL.Func([Telemetry], [], []),
    'resolveAlert' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'setDeviceConfig' : IDL.Func([DeviceConfigInput], [DeviceConfig], []),
    'updateETA' : IDL.Func([ETA], [], []),
  });
};

export const init = ({ IDL }) => { return []; };