/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TelemetryHistory {
    assetId: string;
    readings: Array<Telemetry>;
}
export interface DeviceConfigInput {
    sf: bigint;
    txp: bigint;
    configured_by: string;
    status: boolean;
    mode: bigint;
    device_id: bigint;
    CAN_id: bigint;
    endpoint_URL: string;
    RFID_enable: boolean;
    frequency: bigint;
    client_id: bigint;
    thresholds: Array<[string, string]>;
    config_timestamp: bigint;
    debug_enable: boolean;
    SD_enable: boolean;
}
export interface ETA {
    originPort: string;
    assetId: string;
    destinationPort: string;
    distanceKm: number;
    departedAt: bigint;
    estimatedArrival: bigint;
    currentSpeedKnots: number;
}
export interface CustodyEvent {
    id: string;
    assetId: string;
    notes: string;
    timestamp: bigint;
    location: string;
    custodian: string;
    eventType: EventType;
}
export interface Asset {
    id: string;
    status: AssetStatus;
    destination: string;
    cargoType: CargoType;
    name: string;
    createdAt: bigint;
    origin: string;
    assetType: AssetType;
}
export interface Telemetry {
    id: string;
    latitude: number;
    shockG: number;
    assetId: string;
    temperature: number;
    satelliteSignal: number;
    humidity: number;
    longitude: number;
    timestamp: bigint;
}
export interface DeviceConfig {
    id: bigint;
    sf: bigint;
    txp: bigint;
    configured_by: string;
    status: boolean;
    mode: bigint;
    device_id: bigint;
    created_at: bigint;
    CAN_id: bigint;
    endpoint_URL: string;
    RFID_enable: boolean;
    frequency: bigint;
    client_id: bigint;
    thresholds: Array<[string, string]>;
    config_timestamp: bigint;
    debug_enable: boolean;
    SD_enable: boolean;
}
export interface Alert {
    id: string;
    resolved: boolean;
    alertType: AlertType;
    assetId: string;
    message: string;
    timestamp: bigint;
    severity: AlertSeverity;
}
export interface UserProfile {
    name: string;
}
export enum AlertSeverity {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum AlertType {
    geofenceBreach = "geofenceBreach",
    tempExceeded = "tempExceeded",
    shockDetected = "shockDetected",
    humidityAlert = "humidityAlert",
    signalLost = "signalLost"
}
export enum AssetStatus {
    alert = "alert",
    inTransit = "inTransit",
    delivered = "delivered",
    onHold = "onHold"
}
export enum AssetType {
    truck = "truck",
    aircraft = "aircraft",
    vessel = "vessel",
    container = "container"
}
export enum CargoType {
    equipment = "equipment",
    medical = "medical",
    pharmaceutical = "pharmaceutical"
}
export enum EventType {
    checkpoint = "checkpoint",
    pickup = "pickup",
    delivery = "delivery",
    transfer = "transfer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAsset(asset: Asset): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAlert(alert: Alert): Promise<void>;
    getAsset(id: string): Promise<Asset | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustodyChain(assetId: string): Promise<Array<CustodyEvent>>;
    getETA(assetId: string): Promise<ETA | null>;
    getLatestDeviceConfig(deviceId: bigint): Promise<DeviceConfig | null>;
    getLatestTelemetry(assetId: string): Promise<Telemetry | null>;
    getTelemetryHistory(assetId: string, limit: bigint): Promise<TelemetryHistory>;
    getUnresolvedAlerts(): Promise<Array<Alert>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAssets(): Promise<Array<Asset>>;
    recordCustodyEvent(event: CustodyEvent): Promise<void>;
    recordTelemetry(t: Telemetry): Promise<void>;
    resolveAlert(alertId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedSampleData(): Promise<void>;
    setDeviceConfig(input: DeviceConfigInput): Promise<DeviceConfig>;
    updateETA(eta: ETA): Promise<void>;
}
import type { Alert as _Alert, AlertSeverity as _AlertSeverity, AlertType as _AlertType, Asset as _Asset, AssetStatus as _AssetStatus, AssetType as _AssetType, CargoType as _CargoType, CustodyEvent as _CustodyEvent, DeviceConfig as _DeviceConfig, ETA as _ETA, EventType as _EventType, Telemetry as _Telemetry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAsset(arg0: Asset): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAsset(to_candid_Asset_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAsset(to_candid_Asset_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAlert(arg0: Alert): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(to_candid_Alert_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(to_candid_Alert_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAsset(arg0: string): Promise<Asset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAsset(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAsset(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustodyChain(arg0: string): Promise<Array<CustodyEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustodyChain(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustodyChain(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getETA(arg0: string): Promise<ETA | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getETA(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getETA(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestDeviceConfig(arg0: bigint): Promise<DeviceConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestDeviceConfig(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestDeviceConfig(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestTelemetry(arg0: string): Promise<Telemetry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestTelemetry(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestTelemetry(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTelemetryHistory(arg0: string, arg1: bigint): Promise<TelemetryHistory> {
        if (this.processError) {
            try {
                const result = await this.actor.getTelemetryHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTelemetryHistory(arg0, arg1);
            return result;
        }
    }
    async getUnresolvedAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnresolvedAlerts();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnresolvedAlerts();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAssets(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssets();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssets();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordCustodyEvent(arg0: CustodyEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordCustodyEvent(to_candid_CustodyEvent_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordCustodyEvent(to_candid_CustodyEvent_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordTelemetry(arg0: Telemetry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTelemetry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTelemetry(arg0);
            return result;
        }
    }
    async resolveAlert(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveAlert(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async setDeviceConfig(arg0: DeviceConfigInput): Promise<DeviceConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.setDeviceConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDeviceConfig(arg0);
            return result;
        }
    }
    async updateETA(arg0: ETA): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateETA(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateETA(arg0);
            return result;
        }
    }
}
function from_candid_AlertSeverity_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_AlertType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_AssetStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetStatus): AssetStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_AssetType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetType): AssetType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Asset_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Asset {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_CargoType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CargoType): CargoType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CustodyEvent_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustodyEvent): CustodyEvent {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Asset]): Asset | null {
    return value.length === 0 ? null : from_candid_Asset_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ETA]): ETA | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeviceConfig]): DeviceConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Telemetry]): Telemetry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AssetStatus;
    destination: string;
    cargoType: _CargoType;
    name: string;
    createdAt: bigint;
    origin: string;
    assetType: _AssetType;
}): {
    id: string;
    status: AssetStatus;
    destination: string;
    cargoType: CargoType;
    name: string;
    createdAt: bigint;
    origin: string;
    assetType: AssetType;
} {
    return {
        id: value.id,
        status: from_candid_AssetStatus_n20(_uploadFile, _downloadFile, value.status),
        destination: value.destination,
        cargoType: from_candid_CargoType_n22(_uploadFile, _downloadFile, value.cargoType),
        name: value.name,
        createdAt: value.createdAt,
        origin: value.origin,
        assetType: from_candid_AssetType_n24(_uploadFile, _downloadFile, value.assetType)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    assetId: string;
    notes: string;
    timestamp: bigint;
    location: string;
    custodian: string;
    eventType: _EventType;
}): {
    id: string;
    assetId: string;
    notes: string;
    timestamp: bigint;
    location: string;
    custodian: string;
    eventType: EventType;
} {
    return {
        id: value.id,
        assetId: value.assetId,
        notes: value.notes,
        timestamp: value.timestamp,
        location: value.location,
        custodian: value.custodian,
        eventType: from_candid_EventType_n32(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    resolved: boolean;
    alertType: _AlertType;
    assetId: string;
    message: string;
    timestamp: bigint;
    severity: _AlertSeverity;
}): {
    id: string;
    resolved: boolean;
    alertType: AlertType;
    assetId: string;
    message: string;
    timestamp: bigint;
    severity: AlertSeverity;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        alertType: from_candid_AlertType_n40(_uploadFile, _downloadFile, value.alertType),
        assetId: value.assetId,
        message: value.message,
        timestamp: value.timestamp,
        severity: from_candid_AlertSeverity_n42(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alert: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} | {
    onHold: null;
}): AssetStatus {
    return "alert" in value ? AssetStatus.alert : "inTransit" in value ? AssetStatus.inTransit : "delivered" in value ? AssetStatus.delivered : "onHold" in value ? AssetStatus.onHold : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    equipment: null;
} | {
    medical: null;
} | {
    pharmaceutical: null;
}): CargoType {
    return "equipment" in value ? CargoType.equipment : "medical" in value ? CargoType.medical : "pharmaceutical" in value ? CargoType.pharmaceutical : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    truck: null;
} | {
    aircraft: null;
} | {
    vessel: null;
} | {
    container: null;
}): AssetType {
    return "truck" in value ? AssetType.truck : "aircraft" in value ? AssetType.aircraft : "vessel" in value ? AssetType.vessel : "container" in value ? AssetType.container : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkpoint: null;
} | {
    pickup: null;
} | {
    delivery: null;
} | {
    transfer: null;
}): EventType {
    return "checkpoint" in value ? EventType.checkpoint : "pickup" in value ? EventType.pickup : "delivery" in value ? EventType.delivery : "transfer" in value ? EventType.transfer : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    geofenceBreach: null;
} | {
    tempExceeded: null;
} | {
    shockDetected: null;
} | {
    humidityAlert: null;
} | {
    signalLost: null;
}): AlertType {
    return "geofenceBreach" in value ? AlertType.geofenceBreach : "tempExceeded" in value ? AlertType.tempExceeded : "shockDetected" in value ? AlertType.shockDetected : "humidityAlert" in value ? AlertType.humidityAlert : "signalLost" in value ? AlertType.signalLost : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): AlertSeverity {
    return "low" in value ? AlertSeverity.low : "high" in value ? AlertSeverity.high : "medium" in value ? AlertSeverity.medium : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustodyEvent>): Array<CustodyEvent> {
    return value.map((x)=>from_candid_CustodyEvent_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Asset>): Array<Asset> {
    return value.map((x)=>from_candid_Asset_n18(_uploadFile, _downloadFile, x));
}
function to_candid_AlertSeverity_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): _AlertSeverity {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_AlertType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): _AlertType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Alert_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Alert): _Alert {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_AssetStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetStatus): _AssetStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_AssetType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): _AssetType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Asset_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Asset): _Asset {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CargoType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CargoType): _CargoType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CustodyEvent_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustodyEvent): _CustodyEvent {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_EventType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    resolved: boolean;
    alertType: AlertType;
    assetId: string;
    message: string;
    timestamp: bigint;
    severity: AlertSeverity;
}): {
    id: string;
    resolved: boolean;
    alertType: _AlertType;
    assetId: string;
    message: string;
    timestamp: bigint;
    severity: _AlertSeverity;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        alertType: to_candid_AlertType_n13(_uploadFile, _downloadFile, value.alertType),
        assetId: value.assetId,
        message: value.message,
        timestamp: value.timestamp,
        severity: to_candid_AlertSeverity_n15(_uploadFile, _downloadFile, value.severity)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: AssetStatus;
    destination: string;
    cargoType: CargoType;
    name: string;
    createdAt: bigint;
    origin: string;
    assetType: AssetType;
}): {
    id: string;
    status: _AssetStatus;
    destination: string;
    cargoType: _CargoType;
    name: string;
    createdAt: bigint;
    origin: string;
    assetType: _AssetType;
} {
    return {
        id: value.id,
        status: to_candid_AssetStatus_n3(_uploadFile, _downloadFile, value.status),
        destination: value.destination,
        cargoType: to_candid_CargoType_n5(_uploadFile, _downloadFile, value.cargoType),
        name: value.name,
        createdAt: value.createdAt,
        origin: value.origin,
        assetType: to_candid_AssetType_n7(_uploadFile, _downloadFile, value.assetType)
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    assetId: string;
    notes: string;
    timestamp: bigint;
    location: string;
    custodian: string;
    eventType: EventType;
}): {
    id: string;
    assetId: string;
    notes: string;
    timestamp: bigint;
    location: string;
    custodian: string;
    eventType: _EventType;
} {
    return {
        id: value.id,
        assetId: value.assetId,
        notes: value.notes,
        timestamp: value.timestamp,
        location: value.location,
        custodian: value.custodian,
        eventType: to_candid_EventType_n47(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): {
    geofenceBreach: null;
} | {
    tempExceeded: null;
} | {
    shockDetected: null;
} | {
    humidityAlert: null;
} | {
    signalLost: null;
} {
    return value == AlertType.geofenceBreach ? {
        geofenceBreach: null
    } : value == AlertType.tempExceeded ? {
        tempExceeded: null
    } : value == AlertType.shockDetected ? {
        shockDetected: null
    } : value == AlertType.humidityAlert ? {
        humidityAlert: null
    } : value == AlertType.signalLost ? {
        signalLost: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == AlertSeverity.low ? {
        low: null
    } : value == AlertSeverity.high ? {
        high: null
    } : value == AlertSeverity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetStatus): {
    alert: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} | {
    onHold: null;
} {
    return value == AssetStatus.alert ? {
        alert: null
    } : value == AssetStatus.inTransit ? {
        inTransit: null
    } : value == AssetStatus.delivered ? {
        delivered: null
    } : value == AssetStatus.onHold ? {
        onHold: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    checkpoint: null;
} | {
    pickup: null;
} | {
    delivery: null;
} | {
    transfer: null;
} {
    return value == EventType.checkpoint ? {
        checkpoint: null
    } : value == EventType.pickup ? {
        pickup: null
    } : value == EventType.delivery ? {
        delivery: null
    } : value == EventType.transfer ? {
        transfer: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CargoType): {
    equipment: null;
} | {
    medical: null;
} | {
    pharmaceutical: null;
} {
    return value == CargoType.equipment ? {
        equipment: null
    } : value == CargoType.medical ? {
        medical: null
    } : value == CargoType.pharmaceutical ? {
        pharmaceutical: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): {
    truck: null;
} | {
    aircraft: null;
} | {
    vessel: null;
} | {
    container: null;
} {
    return value == AssetType.truck ? {
        truck: null
    } : value == AssetType.aircraft ? {
        aircraft: null
    } : value == AssetType.vessel ? {
        vessel: null
    } : value == AssetType.container ? {
        container: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
